ALTER TABLE `USER_LEVELS` ADD COLUMN `HOME_SECTION_EDIT` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `USER_LEVELS` ADD COLUMN `HOME_SECTION_VIEW` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `USER_LEVELS` MODIFY `GRADES_ADD` TINYINT(1) DEFAULT '0' NOT NULL;

ALTER TABLE `USER_LEVELS` MODIFY `GRADES_EDIT` TINYINT(1) DEFAULT '0' NOT NULL;

ALTER TABLE `USER_LEVELS` MODIFY `GRADES_VIEW` TINYINT(1) DEFAULT '0' NOT NULL;

ALTER TABLE `USER_LEVELS` MODIFY `GRADES_DELETE` TINYINT(1) DEFAULT '0' NOT NULL;

ALTER TABLE `USER_LEVELS` MODIFY `SUBJECTS_ADD` TINYINT(1) DEFAULT '0' NOT NULL;

ALTER TABLE `USER_LEVELS` MODIFY `SUBJECTS_VIEW` TINYINT(1) DEFAULT '0' NOT NULL;

ALTER TABLE `USER_LEVELS` MODIFY `SUBJECTS_EDIT` TINYINT(1) DEFAULT '0' NOT NULL;

ALTER TABLE `USER_LEVELS` MODIFY `SUBJECTS_DELETE` TINYINT(1) DEFAULT '0' NOT NULL;
